#!/bin/sh
set -e
set -x

for hpp in $(dpkg -L opencl-clhpp-headers | grep '\.hpp$' | sed s%/usr/include/%%)
do
	for std in '' 100 110 120 200 210 220 300
	do
		echo "#include <$hpp>" | g++ -x c++ ${std:+-DCL_HPP_TARGET_OPENCL_VERSION=$std -DCL_HPP_MINIMUM_OPENCL_VERSION=$std} -c -
	done
done
